// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$$0 from ".apps/decohub.ts"
import * as $$$$$$$$$$$$1 from ".apps/site.ts"
import * as $$$$2 from ".loaders/availableIcons.ts"
import * as $$$$3 from ".loaders/icons.ts"
import * as $$$$0 from ".loaders/Layouts/ProductCard.tsx"
import * as $$$$1 from ".loaders/List/Sections.tsx"
import * as $$$$$$$0 from ".sections/Animation/Animation.tsx"
import * as $$$$$$$1 from ".sections/Cards/IconCardsCarousel.tsx"
import * as $$$$$$$2 from ".sections/Cards/IconCardsCarouselWithImage.tsx"
import * as $$$$$$$3 from ".sections/Cards/ImageCardsCarousel.tsx"
import * as $$$$$$$4 from ".sections/Cards/ImageCardsCarouselWithImage.tsx"
import * as $$$$$$$5 from ".sections/Category/CategoryBanner.tsx"
import * as $$$$$$$6 from ".sections/Category/CategoryGrid.tsx"
import * as $$$$$$$7 from ".sections/Category/CategoryList.tsx"
import * as $$$$$$$8 from ".sections/Content/Benefits.tsx"
import * as $$$$$$$9 from ".sections/Content/BlogPosts.tsx"
import * as $$$$$$$10 from ".sections/Content/CallToAction.tsx"
import * as $$$$$$$11 from ".sections/Content/Faq.tsx"
import * as $$$$$$$12 from ".sections/Content/Features.tsx"
import * as $$$$$$$13 from ".sections/Content/Hero.tsx"
import * as $$$$$$$14 from ".sections/Content/ImageSection.tsx"
import * as $$$$$$$15 from ".sections/Content/Intro.tsx"
import * as $$$$$$$16 from ".sections/Content/Logos.tsx"
import * as $$$$$$$17 from ".sections/Content/Partners.tsx"
import * as $$$$$$$18 from ".sections/Content/RichText.tsx"
import * as $$$$$$$19 from ".sections/Content/Table.tsx"
import * as $$$$$$$20 from ".sections/Content/Testimonials.tsx"
import * as $$$$$$$21 from ".sections/Content/TextWithImage.tsx"
import * as $$$$$$$22 from ".sections/Footer/Footer.tsx"
import * as $$$$$$$23 from ".sections/Gallery.tsx"
import * as $$$$$$$24 from ".sections/Header/Header.tsx"
import * as $$$$$$$25 from ".sections/Images/BannerGrid.tsx"
import * as $$$$$$$26 from ".sections/Images/Carousel.tsx"
import * as $$$$$$$27 from ".sections/Images/ImageGallery.tsx"
import * as $$$$$$$28 from ".sections/Images/ShoppableBanner.tsx"
import * as $$$$$$$29 from ".sections/Layout/Container.tsx"
import * as $$$$$$$30 from ".sections/Layout/Flex.tsx"
import * as $$$$$$$31 from ".sections/Layout/Grid.tsx"
import * as $$$$$$$32 from ".sections/Layout/GridItem.tsx"
import * as $$$$$$$33 from ".sections/Links/LinkTree.tsx"
import * as $$$$$$$34 from ".sections/Links/Shortcuts.tsx"
import * as $$$$$$$35 from ".sections/Miscellaneous/CampaignTimer.tsx"
import * as $$$$$$$36 from ".sections/Miscellaneous/CookieConsent.tsx"
import * as $$$$$$$37 from ".sections/Miscellaneous/Slide.tsx"
import * as $$$$$$$38 from ".sections/Newsletter/Newsletter.tsx"
import * as $$$$$$$39 from ".sections/Product/ImageGalleryFrontBack.tsx"
import * as $$$$$$$40 from ".sections/Product/ImageGallerySlider.tsx"
import * as $$$$$$$41 from ".sections/Product/NotFound.tsx"
import * as $$$$$$$42 from ".sections/Product/NotFoundChallenge.tsx"
import * as $$$$$$$43 from ".sections/Product/ProductInfo.tsx"
import * as $$$$$$$44 from ".sections/Product/ProductShelf.tsx"
import * as $$$$$$$45 from ".sections/Product/ProductShelfTabbed.tsx"
import * as $$$$$$$46 from ".sections/Product/SearchResult.tsx"
import * as $$$$$$$47 from ".sections/Product/ShelfWithImage.tsx"
import * as $$$$$$$48 from ".sections/Product/Wishlist.tsx"
import * as $$$$$$$49 from ".sections/Social/InstagramPosts.tsx"
import * as $$$$$$$50 from ".sections/Social/WhatsApp.tsx"
import * as $$$$$$$51 from ".sections/Theme/Theme.tsx"

const manifest = {
    "loaders": {
    "siteloaders/availableIcons.ts": $$$$2,
"siteloaders/icons.ts": $$$$3,
"siteloaders/Layouts/ProductCard.tsx": $$$$0,
"siteloaders/List/Sections.tsx": $$$$1
}
,
"sections": {
    "sitesections/Animation/Animation.tsx": $$$$$$$0,
"sitesections/Cards/IconCardsCarousel.tsx": $$$$$$$1,
"sitesections/Cards/IconCardsCarouselWithImage.tsx": $$$$$$$2,
"sitesections/Cards/ImageCardsCarousel.tsx": $$$$$$$3,
"sitesections/Cards/ImageCardsCarouselWithImage.tsx": $$$$$$$4,
"sitesections/Category/CategoryBanner.tsx": $$$$$$$5,
"sitesections/Category/CategoryGrid.tsx": $$$$$$$6,
"sitesections/Category/CategoryList.tsx": $$$$$$$7,
"sitesections/Content/Benefits.tsx": $$$$$$$8,
"sitesections/Content/BlogPosts.tsx": $$$$$$$9,
"sitesections/Content/CallToAction.tsx": $$$$$$$10,
"sitesections/Content/Faq.tsx": $$$$$$$11,
"sitesections/Content/Features.tsx": $$$$$$$12,
"sitesections/Content/Hero.tsx": $$$$$$$13,
"sitesections/Content/ImageSection.tsx": $$$$$$$14,
"sitesections/Content/Intro.tsx": $$$$$$$15,
"sitesections/Content/Logos.tsx": $$$$$$$16,
"sitesections/Content/Partners.tsx": $$$$$$$17,
"sitesections/Content/RichText.tsx": $$$$$$$18,
"sitesections/Content/Table.tsx": $$$$$$$19,
"sitesections/Content/Testimonials.tsx": $$$$$$$20,
"sitesections/Content/TextWithImage.tsx": $$$$$$$21,
"sitesections/Footer/Footer.tsx": $$$$$$$22,
"sitesections/Gallery.tsx": $$$$$$$23,
"sitesections/Header/Header.tsx": $$$$$$$24,
"sitesections/Images/BannerGrid.tsx": $$$$$$$25,
"sitesections/Images/Carousel.tsx": $$$$$$$26,
"sitesections/Images/ImageGallery.tsx": $$$$$$$27,
"sitesections/Images/ShoppableBanner.tsx": $$$$$$$28,
"sitesections/Layout/Container.tsx": $$$$$$$29,
"sitesections/Layout/Flex.tsx": $$$$$$$30,
"sitesections/Layout/Grid.tsx": $$$$$$$31,
"sitesections/Layout/GridItem.tsx": $$$$$$$32,
"sitesections/Links/LinkTree.tsx": $$$$$$$33,
"sitesections/Links/Shortcuts.tsx": $$$$$$$34,
"sitesections/Miscellaneous/CampaignTimer.tsx": $$$$$$$35,
"sitesections/Miscellaneous/CookieConsent.tsx": $$$$$$$36,
"sitesections/Miscellaneous/Slide.tsx": $$$$$$$37,
"sitesections/Newsletter/Newsletter.tsx": $$$$$$$38,
"sitesections/Product/ImageGalleryFrontBack.tsx": $$$$$$$39,
"sitesections/Product/ImageGallerySlider.tsx": $$$$$$$40,
"sitesections/Product/NotFound.tsx": $$$$$$$41,
"sitesections/Product/NotFoundChallenge.tsx": $$$$$$$42,
"sitesections/Product/ProductInfo.tsx": $$$$$$$43,
"sitesections/Product/ProductShelf.tsx": $$$$$$$44,
"sitesections/Product/ProductShelfTabbed.tsx": $$$$$$$45,
"sitesections/Product/SearchResult.tsx": $$$$$$$46,
"sitesections/Product/ShelfWithImage.tsx": $$$$$$$47,
"sitesections/Product/Wishlist.tsx": $$$$$$$48,
"sitesections/Social/InstagramPosts.tsx": $$$$$$$49,
"sitesections/Social/WhatsApp.tsx": $$$$$$$50,
"sitesections/Theme/Theme.tsx": $$$$$$$51
}
,
"apps": {
    "siteapps/decohub.ts": $$$$$$$$$$$$0,
"siteapps/site.ts": $$$$$$$$$$$$1
}
,
"name": "site",
"baseUrl": import.meta.url
}


export type Manifest = typeof manifest;



export default manifest
